FROM python:3.13-slim

WORKDIR /app
COPY adk-web/ops /app

# RUN apt-get update && apt-get install -y wget unzip && \
#     wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb &&\
#     apt install -y ./google-chrome-stable_current_amd64.deb &&\
#     rm google-chrome-stable_current_amd64.deb && \
#     apt-get clean

RUN pip install -r requirements.txt 

ENTRYPOINT [ "sh", "-c" ]
CMD [ "adk web --host=0.0.0.0 --port=$PORT --allow_origins=$FRONTEND_URL_ORIGIN $AGENTS_DIR" ]
