FROM python:3.13.5-alpine3.22

WORKDIR /app

RUN apk add --no-cache \
    git \
    curl \
    bash && \
    rm -rf /var/cache/apk/* && \
    pip install "google-adk>=1.4.2,<2.0.0" && \
    pip install "a2a-sdk>=0.2.9,<0.3.0"

ENTRYPOINT [ "sh", "-c" ]
CMD [ "adk api_server --host=0.0.0.0 --port=$PORT --allow_origins=$FRONTEND_URL_ORIGIN $AGENTS_DIR" ]
